services:
  app:
    command: sleep infinity
    image: pm-stable
    working_dir: /app
    # privileged: true
    volumes:
    - type: bind
      source: ./testbin
      target: /home/podman/test
    - pm-root:/var/lib/containers
    - pm-user:/home/podman/.local/share/containers
    cap_add:
    - MKNOD
    - SYS_ADMIN
    devices:
    - "/dev/fuse"
    security_opt:
    - label=disable
    - seccomp=unconfined
#     - unmask=/sys/fs/cgroup
# https://github.com/containers/podman/issues/8441
    user: root

volumes:
  pm-root:
  pm-user: