FROM fedora:38

RUN dnf install -y \
  gcc \
  git \
  libcap-devel \
  libcgroup

WORKDIR /tmp/isolate
RUN git clone https://github.com/ioi/isolate.git /tmp/isolate
RUN make install
RUN rm -rf /tmp/*