FROM ubuntu:23.04

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cgroup-lite \
    libcap-dev \
    git

WORKDIR /tmp/isolate
RUN git clone https://github.com/ioi/isolate.git /tmp/isolate
RUN make install
RUN rm -rf /tmp/*